export const MERCADOPAGO_CONFIG = {
  BASE_URL: 'https://api.mercadopago.com' as const,
  SANDBOX_URL: 'https://api.mercadopago.com' as const,
  DEFAULT_CURRENCY: 'BRL' as const,
  SUPPORTED_CURRENCIES: ['BRL', 'ARS', 'CLP', 'COP', 'MXN', 'PEN', 'UYU'] as const,
  SUPPORTED_PAYMENT_METHODS: ['credit_card', 'debit_card', 'pix', 'boleto', 'ticket', 'bank_transfer'] as const,
  
  // Configurações de pagamento
  PAYMENT_CONFIG: {
    statement_descriptor: 'WHATPRESS',
    expiration_date: 7, // dias para vencimento do boleto
    max_installments: 12,
    default_installments: 1,
  },

  // Webhook events
  WEBHOOK_EVENTS: {
    PAYMENT_CREATED: 'payment.created',
    PAYMENT_UPDATED: 'payment.updated',
    PAYMENT_APPROVED: 'payment.approved',
    PAYMENT_REJECTED: 'payment.rejected',
    PAYMENT_CANCELLED: 'payment.cancelled',
    PAYMENT_REFUNDED: 'payment.refunded',
    PAYMENT_CHARGEBACK: 'payment.chargeback',
    PAYMENT_DISPUTE: 'payment.dispute',
    PAYMENT_RECOVERED: 'payment.recovered',
    PAYMENT_WAITING_PAYMENT: 'payment.waiting_payment',
    PAYMENT_IN_PROCESS: 'payment.in_process',
    PAYMENT_PENDING: 'payment.pending',
    PAYMENT_AUTHORIZED: 'payment.authorized',
    PAYMENT_IN_MEDIATION: 'payment.in_mediation',
    PAYMENT_CHARGEBACK_PENDING: 'payment.chargeback_pending',
    PAYMENT_CHARGEBACK_DISPUTE: 'payment.chargeback_dispute',
    PAYMENT_CHARGEBACK_WON: 'payment.chargeback_won',
    PAYMENT_CHARGEBACK_LOST: 'payment.chargeback_lost',
    PAYMENT_PRE_APPROVED: 'payment.pre_approved',
    PAYMENT_AUTHORIZED_EXPIRED: 'payment.authorized_expired',
    PAYMENT_CANCELLED_EXPIRED: 'payment.cancelled_expired',
    PAYMENT_EXPIRED: 'payment.expired',
    PAYMENT_REFUNDED_PARTIAL: 'payment.refunded_partial',
    PAYMENT_REFUNDED_TOTAL: 'payment.refunded_total',
    PAYMENT_REFUNDED_OVERPAID: 'payment.refunded_overpaid',
    PAYMENT_REFUNDED_UNPAID: 'payment.refunded_unpaid',
    PAYMENT_CHARGEBACK_REFUNDED: 'payment.chargeback_refunded',
    PAYMENT_CHARGEBACK_CANCELLED: 'payment.chargeback_cancelled',
    PAYMENT_CHARGEBACK_CHARGED: 'payment.chargeback_charged',
    PAYMENT_CHARGEBACK_UNCHANGED: 'payment.chargeback_unchanged',
    PAYMENT_CHARGEBACK_REVERSED: 'payment.chargeback_reversed',
    PAYMENT_CHARGEBACK_WON_PARTIAL: 'payment.chargeback_won_partial',
    PAYMENT_CHARGEBACK_LOST_PARTIAL: 'payment.chargeback_lost_partial',
    PAYMENT_CHARGEBACK_PENDING_PARTIAL: 'payment.chargeback_pending_partial',
    PAYMENT_CHARGEBACK_DISPUTE_PARTIAL: 'payment.chargeback_dispute_partial',
    PAYMENT_CHARGEBACK_WON_PARTIAL: 'payment.chargeback_won_partial',
    PAYMENT_CHARGEBACK_LOST_PARTIAL: 'payment.chargeback_lost_partial',
    PAYMENT_CHARGEBACK_PENDING_PARTIAL: 'payment.chargeback_pending_partial',
    PAYMENT_CHARGEBACK_DISPUTE_PARTIAL: 'payment.chargeback_dispute_partial',
    PAYMENT_PIX_CREATED: 'payment.pix_created',
    PAYMENT_PIX_EXPIRED: 'payment.pix_expired',
    PAYMENT_PIX_PAID: 'payment.pix_paid',
    PAYMENT_PIX_REFUNDED: 'payment.pix_refunded',
    PAYMENT_PIX_CHARGEBACK: 'payment.pix_chargeback',
    PAYMENT_PIX_DISPUTE: 'payment.pix_dispute',
    PAYMENT_PIX_RECOVERED: 'payment.pix_recovered',
    PAYMENT_PIX_WAITING_PAYMENT: 'payment.pix_waiting_payment',
    PAYMENT_PIX_IN_PROCESS: 'payment.pix_in_process',
    PAYMENT_PIX_PENDING: 'payment.pix_pending',
    PAYMENT_PIX_AUTHORIZED: 'payment.pix_authorized',
    PAYMENT_PIX_IN_MEDIATION: 'payment.pix_in_mediation',
    PAYMENT_PIX_CHARGEBACK_PENDING: 'payment.pix_chargeback_pending',
    PAYMENT_PIX_CHARGEBACK_DISPUTE: 'payment.pix_chargeback_dispute',
    PAYMENT_PIX_CHARGEBACK_WON: 'payment.pix_chargeback_won',
    PAYMENT_PIX_CHARGEBACK_LOST: 'payment.pix_chargeback_lost',
    PAYMENT_PIX_PRE_APPROVED: 'payment.pix_pre_approved',
    PAYMENT_PIX_AUTHORIZED_EXPIRED: 'payment.pix_authorized_expired',
    PAYMENT_PIX_CANCELLED_EXPIRED: 'payment.pix_cancelled_expired',
    PAYMENT_PIX_EXPIRED: 'payment.pix_expired',
    PAYMENT_PIX_REFUNDED_PARTIAL: 'payment.pix_refunded_partial',
    PAYMENT_PIX_REFUNDED_TOTAL: 'payment.pix_refunded_total',
    PAYMENT_PIX_REFUNDED_OVERPAID: 'payment.pix_refunded_overpaid',
    PAYMENT_PIX_REFUNDED_UNPAID: 'payment.pix_refunded_unpaid',
    PAYMENT_PIX_CHARGEBACK_REFUNDED: 'payment.pix_chargeback_refunded',
    PAYMENT_PIX_CHARGEBACK_CANCELLED: 'payment.pix_chargeback_cancelled',
    PAYMENT_PIX_CHARGEBACK_CHARGED: 'payment.pix_chargeback_charged',
    PAYMENT_PIX_CHARGEBACK_UNCHANGED: 'payment.pix_chargeback_unchanged',
    PAYMENT_PIX_CHARGEBACK_REVERSED: 'payment.pix_chargeback_reversed',
    PAYMENT_PIX_CHARGEBACK_WON_PARTIAL: 'payment.pix_chargeback_won_partial',
    PAYMENT_PIX_CHARGEBACK_LOST_PARTIAL: 'payment.pix_chargeback_lost_partial',
    PAYMENT_PIX_CHARGEBACK_PENDING_PARTIAL: 'payment.pix_chargeback_pending_partial',
    PAYMENT_PIX_CHARGEBACK_DISPUTE_PARTIAL: 'payment.pix_chargeback_dispute_partial',
    PAYMENT_BOLETO_CREATED: 'payment.boleto_created',
    PAYMENT_BOLETO_EXPIRED: 'payment.boleto_expired',
    PAYMENT_BOLETO_PAID: 'payment.boleto_paid',
    PAYMENT_BOLETO_REFUNDED: 'payment.boleto_refunded',
    PAYMENT_BOLETO_CHARGEBACK: 'payment.boleto_chargeback',
    PAYMENT_BOLETO_DISPUTE: 'payment.boleto_dispute',
    PAYMENT_BOLETO_RECOVERED: 'payment.boleto_recovered',
    PAYMENT_BOLETO_WAITING_PAYMENT: 'payment.boleto_waiting_payment',
    PAYMENT_BOLETO_IN_PROCESS: 'payment.boleto_in_process',
    PAYMENT_BOLETO_PENDING: 'payment.boleto_pending',
    PAYMENT_BOLETO_AUTHORIZED: 'payment.boleto_authorized',
    PAYMENT_BOLETO_IN_MEDIATION: 'payment.boleto_in_mediation',
    PAYMENT_BOLETO_CHARGEBACK_PENDING: 'payment.boleto_chargeback_pending',
    PAYMENT_BOLETO_CHARGEBACK_DISPUTE: 'payment.boleto_chargeback_dispute',
    PAYMENT_BOLETO_CHARGEBACK_WON: 'payment.boleto_chargeback_won',
    PAYMENT_BOLETO_CHARGEBACK_LOST: 'payment.boleto_chargeback_lost',
    PAYMENT_BOLETO_PRE_APPROVED: 'payment.boleto_pre_approved',
    PAYMENT_BOLETO_AUTHORIZED_EXPIRED: 'payment.boleto_authorized_expired',
    PAYMENT_BOLETO_CANCELLED_EXPIRED: 'payment.boleto_cancelled_expired',
    PAYMENT_BOLETO_EXPIRED: 'payment.boleto_expired',
    PAYMENT_BOLETO_REFUNDED_PARTIAL: 'payment.boleto_refunded_partial',
    PAYMENT_BOLETO_REFUNDED_TOTAL: 'payment.boleto_refunded_total',
    PAYMENT_BOLETO_REFUNDED_OVERPAID: 'payment.boleto_refunded_overpaid',
    PAYMENT_BOLETO_REFUNDED_UNPAID: 'payment.boleto_refunded_unpaid',
    PAYMENT_BOLETO_CHARGEBACK_REFUNDED: 'payment.boleto_chargeback_refunded',
    PAYMENT_BOLETO_CHARGEBACK_CANCELLED: 'payment.boleto_chargeback_cancelled',
    PAYMENT_BOLETO_CHARGEBACK_CHARGED: 'payment.boleto_chargeback_charged',
    PAYMENT_BOLETO_CHARGEBACK_UNCHANGED: 'payment.boleto_chargeback_unchanged',
    PAYMENT_BOLETO_CHARGEBACK_REVERSED: 'payment.boleto_chargeback_reversed',
    PAYMENT_BOLETO_CHARGEBACK_WON_PARTIAL: 'payment.boleto_chargeback_won_partial',
    PAYMENT_BOLETO_CHARGEBACK_LOST_PARTIAL: 'payment.boleto_chargeback_lost_partial',
    PAYMENT_BOLETO_CHARGEBACK_PENDING_PARTIAL: 'payment.boleto_chargeback_pending_partial',
    PAYMENT_BOLETO_CHARGEBACK_DISPUTE_PARTIAL: 'payment.boleto_chargeback_dispute_partial',
  } as const,

  // Error codes
  ERROR_CODES: {
    INVALID_API_KEY: 'invalid_api_key',
    INVALID_REQUEST: 'invalid_request',
    INVALID_PAYMENT: 'invalid_payment',
    PAYMENT_NOT_FOUND: 'payment_not_found',
    CUSTOMER_NOT_FOUND: 'customer_not_found',
    CARD_NOT_FOUND: 'card_not_found',
    CARD_TOKEN_NOT_FOUND: 'card_token_not_found',
    INVALID_CARD_TOKEN: 'invalid_card_token',
    INVALID_CARD: 'invalid_card',
    INVALID_PAYMENT_METHOD: 'invalid_payment_method',
    INVALID_INSTALLMENTS: 'invalid_installments',
    INVALID_AMOUNT: 'invalid_amount',
    INVALID_CURRENCY: 'invalid_currency',
    INVALID_DESCRIPTION: 'invalid_description',
    INVALID_EXTERNAL_REFERENCE: 'invalid_external_reference',
    INVALID_STATEMENT_DESCRIPTOR: 'invalid_statement_descriptor',
    INVALID_CALLBACK_URL: 'invalid_callback_url',
    INVALID_SUCCESS_URL: 'invalid_success_url',
    INVALID_FAILURE_URL: 'invalid_failure_url',
    INVALID_NOTIFICATION_URL: 'invalid_notification_url',
    INVALID_EXPIRATION_DATE: 'invalid_expiration_date',
    INVALID_PAYMENT_TYPE: 'invalid_payment_type',
    INVALID_BIN: 'invalid_bin',
    INVALID_ISSUER_ID: 'invalid_issuer_id',
    INVALID_PROCESSING_MODE: 'invalid_processing_mode',
    INVALID_CAPTURE: 'invalid_capture',
    INVALID_TOKEN: 'invalid_token',
    INVALID_EMAIL: 'invalid_email',
    INVALID_IDENTIFICATION_TYPE: 'invalid_identification_type',
    INVALID_IDENTIFICATION_NUMBER: 'invalid_identification_number',
    INVALID_CARDHOLDER_NAME: 'invalid_cardholder_name',
    INVALID_CARD_EXPIRATION_MONTH: 'invalid_card_expiration_month',
    INVALID_CARD_EXPIRATION_YEAR: 'invalid_card_expiration_year',
    INVALID_CARD_SECURITY_CODE: 'invalid_card_security_code',
    INVALID_CARD_NUMBER: 'invalid_card_number',
    INVALID_CARD_ISSUER: 'invalid_card_issuer',
    INVALID_CARD_TYPE: 'invalid_card_type',
    INVALID_CARDHOLDER_IDENTIFICATION_TYPE: 'invalid_cardholder_identification_type',
    INVALID_CARDHOLDER_IDENTIFICATION_NUMBER: 'invalid_cardholder_identification_number',
    INVALID_PAYER_EMAIL: 'invalid_payer_email',
    INVALID_PAYER_IDENTIFICATION_TYPE: 'invalid_payer_identification_type',
    INVALID_PAYER_IDENTIFICATION_NUMBER: 'invalid_payer_identification_number',
    INVALID_PAYER_NAME: 'invalid_payer_name',
    INVALID_PAYER_SURNAME: 'invalid_payer_surname',
    INVALID_PAYER_PHONE_AREA_CODE: 'invalid_payer_phone_area_code',
    INVALID_PAYER_PHONE_NUMBER: 'invalid_payer_phone_number',
    INVALID_PAYER_ADDRESS_STREET_NAME: 'invalid_payer_address_street_name',
    INVALID_PAYER_ADDRESS_STREET_NUMBER: 'invalid_payer_address_street_number',
    INVALID_PAYER_ADDRESS_ZIP_CODE: 'invalid_payer_address_zip_code',
    INVALID_PAYER_ADDRESS_FLOOR: 'invalid_payer_address_floor',
    INVALID_PAYER_ADDRESS_APARTMENT: 'invalid_payer_address_apartment',
    INVALID_PAYER_ADDRESS_CITY_NAME: 'invalid_payer_address_city_name',
    INVALID_PAYER_ADDRESS_STATE_NAME: 'invalid_payer_address_state_name',
    INVALID_PAYER_ADDRESS_COUNTRY_NAME: 'invalid_payer_address_country_name',
    INVALID_PAYER_ADDRESS_ADDITIONAL_INFO: 'invalid_payer_address_additional_info',
    INVALID_PAYER_ADDRESS_REFERENCE: 'invalid_payer_address_reference',
    INVALID_PAYER_ADDRESS_NEIGHBORHOOD: 'invalid_payer_address_neighborhood',
    INVALID_PAYER_ADDRESS_MUNICIPALITY: 'invalid_payer_address_municipality',
    INVALID_PAYER_ADDRESS_FEDERAL_UNIT: 'invalid_payer_address_federal_unit',
    INVALID_PAYER_ADDRESS_TYPE: 'invalid_payer_address_type',
    INVALID_PAYER_ADDRESS_ID: 'invalid_payer_address_id',
    INVALID_PAYER_ADDRESS_LATITUDE: 'invalid_payer_address_latitude',
    INVALID_PAYER_ADDRESS_LONGITUDE: 'invalid_payer_address_longitude',
    INVALID_PAYER_ADDRESS_LOCATION_ACCURACY: 'invalid_payer_address_location_accuracy',
    INVALID_PAYER_ADDRESS_LOCATION_ACCURACY_TYPE: 'invalid_payer_address_location_accuracy_type',
    INVALID_PAYER_ADDRESS_LOCATION_SOURCE: 'invalid_payer_address_location_source',
    INVALID_PAYER_ADDRESS_LOCATION_LAST_UPDATED: 'invalid_payer_address_location_last_updated',
    INVALID_PAYER_ADDRESS_LOCATION_LAST_UPDATED_TYPE: 'invalid_payer_address_location_last_updated_type',
    INVALID_PAYER_ADDRESS_LOCATION_LAST_UPDATED_SOURCE: 'invalid_payer_address_location_last_updated_source',
  } as const,

  // Retry configuration
  RETRY_CONFIG: {
    max_attempts: 3,
    backoff_multiplier: 2,
    initial_delay: 1000,
  },
} as const;

export type MercadoPagoConfig = typeof MERCADOPAGO_CONFIG;